bot.name=KogtetochkaaBot
bot.token=6054634402:AAGqQkRMPEW8EijYnDb0BkgIc9p72B7K2OU

#db related settings

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/kg_bot_db
spring.datasource.username=postgre
spring.datasource.password=Fancytrumpet132
